### PR TITLE
Fix readme typos

### LINKED ISSUE #8: there is no .filter() function
The Readme mentions a `.filter()` function, however it doesn't seem to exist in the source code!

### PR DESCRIPTION
**Pull request by TooTallNate**
Closes #8.

### CODE REVIEW

**Comment by TooTallNate** [comment]
@MatthewMueller ping

**Comment by MatthewMueller** [comment]
thanks @TooTallNate!

**Comment by MatthewMueller** [comment]
I think `it.reject(fn)` should cover the filter. Must have been messing with the names.

Dunno where I got the `Node.ElementNode` stuff though ahha

**Comment by TooTallNate** [comment]
Hahah. Miss you bro. Happy new year :smile_cat:

**Comment by MatthewMueller** [comment]
Miss you too dude! Hope you had a great holiday. We gotta meet up soon.

Btw, I want to show you what I've been up to some time in the next couple days. Looking for some solid feedback. Keep an eye on your inbox! :-D

**Pull request merged**
